### PR TITLE
74-Program Restriction cannot be retrieved from project

### LINKED ISSUE #74: [BUG] - Program Restriction cannot be retrieved from project
**Describe the bug**
Program restriction can be added to a project but they cannot be retrieved due to a lazyinitializationexecption

**To Reproduce**
1. Create a test that adds a new project with program restrictions
2. Find the project and try call getProgramRestrictions()

**Expected behavior**
We should be able to retrieve the list of program restrictions

**Actual behavior**
LazyInitializationException

### PR DESCRIPTION
**Pull request by ShasRanasinghe**
## Proposed changes

Programs were implemented as an enum before and the relationship between program and project was kept in a join table. This introduced the bug of not being able to retrieve programs from the project entity. To resolve this and hopefully make programs into a more manageable entity, this issue converted programs into an entity with a many to many relationship with projects

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (a non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._
- [x] The title is in the format [Issue number]-[Issue Title]
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have moved the issue to the “Need review” columns of projects

## Tasks completed
- Converted Program enum into an entity class with a corresponding repository and service class
- Initialize the program table programmatically using a data loader upon application startup
- /professor and /projects view edited to display the program restrictions of a project
- Updated the database schema diagram
- Added tests to test the program service class and adding of program restrictions to a project

## Tests performed
- Tested adding a project with program restrictions
- Tested editing a projects program restrictions
- Tested adding and removing programs
- Tested that a projects program restrictions are displayed in the /professor and /projects views

## Known issues
Create issue for known issues and link them in the pull request

Closes #74 #82 

## Screenshots (if applicable)
image
image

## Must Do Before Approving
_Put an `x` in the boxes that apply.
- [x] Review the code changes and check for code smells and or make comments if needed

Put an `x` in the box below if you need the reviewer to double check the front-end changes you made
- [x] Tophat Needed (Steps: check out the branch and run the application locally to determine if the front-end change looks the same as in this PR)

### CODE REVIEW

**Comment by seanrt** [comment]
As far as I can tell, this PR replaces the Program enum with a Program class. When the web app starts, a Program entity is created and persisted for each of the SYSC department programs. This seems very convoluted and prone to causing downstream errors. Why can't we just use an enum to hold all the programs?

**Comment by ShasRanasinghe** [comment]
@seanrt it's not really that we can't use enums, because that's how I did it before, but I ran into the issue of not being able to get the list of program restrictions from the project entity.

When I talked about how to approach this with Michael he suggest I make the programs into entities and have a many to many relationship, which is what I did here.

It does seem like overkill for something that could be an enum but with programs as an entity these can be added and removed by the coordinator as needed. Which you cant do with enums. You would need to change the code to add or remove programs.

And I do admit adding the data through the dataloader may not be the best practice, but as much as I tried I never figured out how to set up the schema using spring but have data be imported from a file. As far as I can tell for data to be imported from a file, the schema also needs to be generated from a file.

Also, what errors are you referring to by downstream errors?

**Comment by seanrt** [comment]
I've been working on #95 , which accesses the program restrictions as they are currently implemented using enums. The enum approach appears to be working at the moment. IMO the change from using enums to entities to represent programs is unnecessary given that the current approach is working. It also requires far fewer files and configuration. @arungalva  @blessingomotayo  please chime in with your thoughts.

**Comment by arungalva** [comment]
I think this should be fine especially since he's already got it working with unit and integration tests. How much work would it be to change it on your pr @seanrt ? Also, I think this PR is missing unit test for the project entity @ShasRanasinghe

**Comment by ShasRanasinghe** [comment]
@arungalva I changed an existing project test to see if the the project has the added programs. You'll see it in the professor controller test changes

**Comment by seanrt** [comment]
I think we can close this PR

**Comment by seanrt** [comment]
Closing this because we were able to make the program selections work using Enums. The move to entities was not necessary.

**Pull request closed without merging**
