### PR TITLE
76-Add the ability to create new announcements

### LINKED ISSUE #76: Add the ability to create new announcements
**Is your feature request related to a problem? Please describe.**
There should be a way to add announcements to the announcements page

**Describe the solution you'd like**
Add a button at the bottom of the announcements page
This button should open up a new page that lets you enter the details of the header.
These should be displayed in the announcements page

**Acceptance criteria**

- [x] Add announcement button
- [x] Add announcement form
- [x] Database table that holds announcements
- [x] Tests that ensure added announcements are persisted in the database

### PR DESCRIPTION
**Pull request by ShasRanasinghe**
## Proposed changes

There should be a way to add, edit and delete announcements
The coordinator should be able to do this while the others should be able to view it

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._
- [x] The title is in the format [Issue number]-[Issue Title]
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have moved issue to the “Need review” columns of projects

## Tasks completed
- Added an announcement entity
- Created buttons to add edit and remove announcements
- Created pages to add and edit announcements
- Created tested to test that announcements are added, and removed correctly from the database
- Added the COORDINATOR role
- Limited the access to announcement resources to only coordinators 
- Only coordinators are able to see the add, edit and delete buttons in the announcement page

## Tests performed
- Tested that the announcements are shown to all users
- Tested that the add, edit, and delete buttons are shown to the coordinators
- Tested that announcements can be added, edited and deleted
- Tested that non coordinators attempting to add, edit or delete will be shown the /accessdenied page 

## Screenshots (if applicable)
Displayed to coordinators
image
Displayed to non coordinators
image
Add Announcement
image
Edit Announcement
image

## Must Do Before Approving
_Put an `x` in the boxes that apply.
- [x] Review the code changes and check for code smells and or make comments if needed

Put an `x` in the box below if you need the reviewer to double check the front-end changes you made
- [x] Tophat Needed (Steps: checkout the branch and run the application locally to determine if the front-end change looks the same as in this PR)

### CODE REVIEW

**Comment by seanrt** [comment]
image
Feels bad man

**Comment by seanrt** [comment]
I'll try to muster up the motivation go over the code later

**Comment by seanrt** [comment]
So this PR is forked off of #92 right? Which PR should be merged first?

**Comment by ShasRanasinghe** [comment]
@seanrt yeah #92 needs to go in first

**Comment by ShasRanasinghe** [comment]
Closing pull request to rebase to current master

**Pull request closed without merging**
