### PR TITLE
[4] - Added the basic student view

### LINKED ISSUE #4: Create a student view
create a controller that renders a basic student view that shows
- [ ] The project you have applied to
- [ ] The other students who have applied to the same project

### PR DESCRIPTION
**Pull request by seanrt**
## Proposed changes
Added a simple student controller and view.

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] The title is in the format [Issue number]-[Issue Title]
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have moved issue to the “Need review” columns of projects

## Tasks completed
- Added a simple student template view
- Added a simple StudentController

## Tests performed
- Loaded the page at /student

## Known issues
First step towards #4 

## Screenshots (if applicable)
image

## Must Do Before Approving
- [x] Review the code changes and check for code smells and or make comments if needed
- [x] Tophat Needed (Steps: checkout the branch and run the application locally to determine if the front-end change looks the same as in this PR)

### CODE REVIEW

**Comment by ShasRanasinghe** [comment]
@seanrt Should we have like a button or something to take us to /student?

**Comment by blessingomotayo** [comment]
The PR shouldn't close issue 4

**Comment by seanrt** [comment]
> The PR shouldn't close issue 4

Why shouldn't this close issue 4? Issue 4 is for a basic non-functional student view, which this PR provides.



> @seanrt Should we have like a button or something to take us to /student?

Sounds good, I'll add the button.



> Might need to add a quick test to see if the page loads up

Will do.

**Comment by blessingomotayo** [comment]
Issue 4 requires you to do the following:
 - The project you have applied to
  - The other students who have applied to the same project
  - Button to upload files
  - Deadline for upload

**Comment by seanrt** [comment]
> Issue 4 requires you to do the following:
> 
>     * The project you have applied to
> 
>     * The other students who have applied to the same project
> 
>     * Button to upload files
> 
>     * Deadline for upload

That makes sense. Also Github won't let me directly reply to your comments, feels bad.

**Pull request merged**
