### PR TITLE
54 - Removed the clicking functionality for the 'Engineering Project Logo'

### LINKED ISSUE #54: [BUG] - Make 'Engineering Project' button in the header not clickable
**Describe the bug**
The Nav bar 'Engineering Project' is clickable but it shouldn't be.

**To Reproduce**
1. Go to '/'
2. Click on 'Engineering Project' in the navigation bar
3. Observe that it does nothing.

**Expected behavior**
Shouldn't be able to click on it
**Actual behavior**
It is clickable
**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by blessingomotayo**
## Proposed changes
Removed the clicking functionality for the 'Engineering Project Logo' in the naw bar

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._
- [x] The title is in the format [Issue number]-[Issue Title]
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have moved issue to the “Need review” columns of projects

## Tasks completed
- Removed the clicking functionality for the 'Engineering Project Logo'

## Tests performed
- Checked to see if I am unable to click on it

## Known issues
Create issue for known issues and link them in the pull request

Closes #54 

## Screenshots (if applicable)
Include screenshots of the front-end changes that were made

## Must Do Before Approving
_Put an `x` in the boxes that apply.
- [x] Review the code changes and check for code smells and or make comments if needed

Put an `x` in the box below if you need the reviewer to double check the front-end changes you made
- [x] Tophat Needed (Steps: checkout the branch and run the application locally to determine if the front-end change looks the same as in this PR)

### CODE REVIEW

**Comment by arungalva** [comment]
Instead of removing the link, doesn't it make more sense to redirect the user to the home page when they click the logo?

**Comment by blessingomotayo** [comment]
There already is a 'Home' button that is clear enough for the users to click on to know it goes to the home page if needed. Making it logo go to the home page might be redundant a little. However, I see what you mean by letting it go to the home page. Some website do allow that functionality

**Comment by arungalva** [comment]
For me, its natural to think that it should go to the homepage as most if not all websites do that. what do you guys think @ShasRanasinghe @seanrt

**Comment by blessingomotayo** [comment]
Then we can remove 'Home' in the naw bar

**Pull request merged**
